name: vgv_coffee_machine
description: Flutter project that allows to save favourite coffee pictures
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  auto_route: ^5.0.2
  bloc: ^8.1.0
  cached_network_image: ^3.2.2
  dartz: ^0.10.1
  dio: ^4.0.6
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^2.2.0
  get_it: ^7.2.0
  injectable: ^1.5.4
  salomon_bottom_bar: ^3.3.1
  shared_preferences: ^2.0.15
  swipe_cards: ^1.0.0

dev_dependencies:
  auto_route_generator: ^5.0.2
  bloc_test: ^9.1.0
  build_runner: ^2.3.0
  collection: ^1.16.0
  dependency_validator: ^3.2.2
  flutter_launcher_icons: ^0.10.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.2.0
  injectable_generator: ^1.5.5
  integration_test:
    sdk: flutter
  json_serializable: ^6.5.4
  mocktail: ^0.3.0

flutter:
  uses-material-design: true
  generate: true

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/launcher_icon.png"